apiVersion: v1
kind: Service
metadata:
  name: testproxy-2
  labels:
    app: testproxy-2
spec:
  type: ClusterIP
  selector:
    openvpn: vpn.example.com
  ports:
  - port: 8082
    targetPort: 8082
